#!/bin/bash
#SBATCH --job-name=BETA_WKFLW
#SBATCH -N 1
#SBATCH -c 1
#SBATCH -t 24:00:00
## %A == SLURM_ARRAY_JOB_ID
#SBATCH -o /projects/niblab/bids_projects/Experiments/Bevel/error_files/workflow_out.txt
#SBATCH -e /projects/niblab/bids_projects/Experiments/Bevel/error_files/workflow_err.txt

~/anaconda3/bin/anaconda /projects/niblab/bids_projects/Experiments/Bevel/derivatives/code/betaseries_workflow.py




