#!/bin/bash
#SBATCH --job-name=BETA_BEVEL
#SBATCH -N 1
#SBATCH -c 1
#SBATCH -t 24:00:00
## %A == SLURM_ARRAY_JOB_ID
## %a == SLURM_ARRAY_TASK_ID
#SBATCH -o /projects/niblab/bids_projects/Experiments/Bevel/error_files/feat1_beta_bevel_%a_%A_out.txt
#SBATCH -e /projects/niblab/bids_projects/Experiments/Bevel/error_files/feat1_beta_bevel_%a_%A_err.txt

if [ ${SLURM_ARRAY_TASK_ID} -lt 10 ]; then
    sub="sub-00${SLURM_ARRAY_TASK_ID}"
else
    sub="sub-0${SLURM_ARRAY_TASK_ID}"
fi

RUN1=(/projects/niblab/bids_projects/Experiments/Bevel/derivatives/$sub/func/Analysis/beta/run-1/design_files/*.fsf)
RUN2=(/projects/niblab/bids_projects/Experiments/Bevel/derivatives/$sub/func/Analysis/beta/run-2/design_files/*.fsf)
RUN3=(/projects/niblab/bids_projects/Experiments/Bevel/derivatives/$sub/func/Analysis/beta/run-3/design_files/*.fsf)
RUN4=(/projects/niblab/bids_projects/Experiments/Bevel/derivatives/$sub/func/Analysis/beta/run-4/design_files/*.fsf)


for f in ${RUN1[@]}; do
    /projects/niblab/modules/software/fsl/5.0.10/bin/feat $f &
done

for f in ${RUN2[@]}; do
    /projects/niblab/modules/software/fsl/5.0.10/bin/feat $f &
done

for f in ${RUN3[@]}; do
    /projects/niblab/modules/software/fsl/5.0.10/bin/feat $f &
done

for f in ${RUN4[@]}; do
    /projects/niblab/modules/software/fsl/5.0.10/bin/feat $f &
done

